quandl_list = {"blockchain_alt_tickers":["BCHAIN/MKPRU", "BCHAIN/TRVOU", "BCHAIN/DIFF", 
            "BCHAIN/AVBLS", "BCHAIN/ATRCT", "BCHAIN/MIREV",
            "BCHAIN/HRATE", "BCHAIN/CPTRA", "BCHAIN/CPTRV", "BCHAIN/ETRVU",
            "BCHAIN/ETRAV", "BCHAIN/TOUTV", "BCHAIN/NTRBL", "BCHAIN/NADDU",
            "BCHAIN/NTREP", "BCHAIN/NTRAN", "BCHAIN/TRFUS", "BCHAIN/MKTCP", "BCHAIN/MWNTD",
            "BCHAIN/MWTRV", "BCHAIN/BCDDY", "BCHAIN/BCDDM", "BCHAIN/BCDDW",
            "BCHAIN/BCDDE", "BCHAIN/TVTVR", "BCHAIN/NETDF", "BCHAIN/MIOPM"],
            "blockchain_alt_names":["Bitcoin Market Price USD", "Bitcoin USD Exchange Trade Volume",
            "Bitcoin Difficulty", "Bitcoin Average Block Size", "Bitcoin Median Transaction Confirmation Time",
            "Bitcoin Miners Revenue", "Bitcoin Hash Rate", "Bitcoin Cost per Transaction",
            "Bitcoin Cost % of Transaction Volume", "Bitcoin Estimated Transaction Volume USD",
            "Bitcoin Estimated Transaction Volume", "Bitcoin Total Output Volume",
            "Bitcoin Number of Transaction per Block", "Bitcoin Number of Unique Bitcoin Addresses Used",
            "Bitcoin Number of Transactions Excluding Popular Addresses", "Bitcoin Number of Transactions",
            "Bitcoin Total Transaction Fees USD", "Bitcoin Market Capitalization",
            "Bitcoin My Wallet Number of Transaction Per Day", "Bitcoin My Wallet Transaction Volume",
            "Bitcoin Days Destroyed (Minimum Age 1 Year)", "Bitcoin Days Destroyed (Minimum Age 1 Month)",
            "Bitcoin Days Destroyed (Minimum Age 1 Week)", "Bitcoin Days Destroyed",
            "Bitcoin Trade Volume vs Transaction Volume Ratio", "Bitcoin Network Deficit", 
            "Bitcoin Mining Operating Margin"]}

crypto_list = {"ticker": ["BTC", "ETH", "LTC", "BCH", "DOGE", "USDT"], 
"name": ["Bitcoin", "Ether", "Litecoin", "Bitcoin Cash", "Dogecoin", "Tether"]}

etf_list = {"ticker": ["BITO", "BTF", "GBTC", "XBTF", "BITS", "BLOK", "BLCN", "LEGR", "BITQ", "KOIN", "DAPP", "ARKF"],
            "name": ["ProShares Bitcoin Strategy ETF", "Valkyrie Bitcoin Strategy ETF", "Grayscale Bitcoin Trust (BTC)",
                    "VanEck Bitcoin Strategy ETF", "Global X Blockchain & Bitcoin Strategy ETF",
                    "Amplify Transformational Data Sharing ETF", "Siren Nasdaq NexGen Economy ETF",
                    "First Trust Indxx Innovative Transaction & Process ETF", "Bitwise Crypto Industry Innovators ETF",
                    "Capital Link Global Fintech Leaders ETF", "VanEck Digital Transformation ETF", 
                    "VanEck Digital Transformation ETF", "ARK Fintech Innovation ETF"],
           "exchange": ["NYSEArca", "NasdaqGM", "Other OTC", "BATS", "NasdaqGM", "NYSEArca", "NasdaqGM",
                       "NasdaqGM", "NYSEArca", "NYSEArca", "NasdaqGM", "NYSEArca"]}


fred_list = {"fred_tickers":["TB3MS", "CPIAUCSL", "CPALTT01USM657N", "FEDFUNDS", "PALLFNFINDEXQ",
"PNRGINDEXM", "W068RCQ027SBEA", "T10YIE", "T5YIE", "T5YIFR", "M1SL", "M2SL", "DGS10", "DFII10",
"HOUST", "PAYEMS", "PCE", "PCEC96", "INVCMRMT", "UNRATE", "NROU", "GDP", "GVZCLS", "MORTGAGE30US"],
            "fred_names":["3-Month Treasury Bill Secondary Market Rate, Discount Basis",
            "Consumer Price Index for All Urban Consumers: All Items in U.S. City Average",
            "Consumer Price Index: Total All Items for the United States",
            "Federal Funds Effective Rate", "Global Price Index of All Commodities",
            "Global price of Energy index", "Government total expenditures",
            "10-Year Breakeven Inflation Rate", "5-Year Breakeven Inflation Rate",
            "5-Year, 5-Year Forward Inflation Expectation Rate", "M1", "M2",
            "Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity, Quoted on an Investment Basis",
            "Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity, Quoted on an Investment Basis, Inflation-Indexed",
            "New Privately-Owned Housing Units Started: Total Units",
            "All Employees, Total Nonfarm", "Personal Consumption Expenditures", 
            "Real Personal Consumption Expenditures", "Real Manufacturing and Trade Inventories",
            "Unemployment Rate", "Noncyclical Rate of Unemployment", "Gross Domestic Product",
            "CBOE Gold ETF Volatility Index", "30-Year Fixed Rate Mortgage Average in the United States"]}